### ISSUE TITLE
Deprecated in PHP 8.2

### ISSUE THREAD

**Issue by ipermediastudio** [iubenda/iubenda-cookie-class#14]
Hello,

in PHP Version 8.2.10 the iubenda.class.php is giving me the following 2 Deprecated messages:
Deprecated: Creation of dynamic property iubendaParser::$original_content_page is deprecated in iubenda.class.php on line 184
Deprecated: Creation of dynamic property iubendaParser::$content_page is deprecated in iubenda.class.php on line 185

**Comment by bafi** [comment]
Resolved in V 14.1.15
